name: Pyrefly Type Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-full.txt ]; then pip install -r requirements-full.txt; else pip install -r requirements.txt; fi
          pip install pyrefly

      - name: Run Pyrefly check
        run: pyrefly check
