name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11', '3.12' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-full.txt ]; then pip install -r requirements-full.txt; else pip install -r requirements.txt pyyaml; fi

      - name: Run tests
        run: pytest -q

      - name: Run Pyrefly type check
        run: |
          pip install pyrefly
          pyrefly check
